

name: "macOS CI workflow"


on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month


jobs:

  macos-latest:
      name: "macos-latest 10.15.7"
      runs-on: macos-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "brew update"
        run: brew update      
      - name: "check on brew version"
        run: brew --version   #Homebrew 2.5.12   
      - name: "Get OS X System Version"
        run: sw_vers       
      - name: "Get Mac System Details with system_profiler"
        run: system_profiler | more  
      - name: "osfingerprinting"
        run: uname -a    
        # cuckoo    
        # Installing Python libraries (on Mac OS X)
        # https://cuckoo.sh/docs/installation/host/requirements.html 
      - name: "cuckoo - Installing Python libraries"
        run: brew install libmagic cairo pango openssl
      - name: "cuckoo - expose the openssl header files in the standard GCC/Clang include directory"
        run: cd /usr/local/include && ln -s ../opt/openssl/include/openssl .                                         


  macos-110:
      name: "macos-11.4"
      runs-on: macos-11.0 # ProductVersion 11.4
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "brew update"
        run: brew update      
      - name: "check on brew version"
        run: brew --version   #Homebrew 2.5.12   
      - name: "Get OS X System Version"
        run: sw_vers       
      - name: "Get Mac System Details with system_profiler"
        run: system_profiler | more  
      - name: "osfingerprinting"
        run: uname -a 
        # cuckoo    
        # Installing Python libraries (on Mac OS X)
        # https://cuckoo.sh/docs/installation/host/requirements.html                            
      - name: "cuckoo - Installing Python libraries"
        run: brew install libmagic cairo pango openssl
      - name: "cuckoo - expose the openssl header files in the standard GCC/Clang include directory"
        run: cd /usr/local/include && ln -s ../opt/openssl/include/openssl .  

  macos-1015:
      name: "macos-10.15.7"
      runs-on: macos-10.15 # ProductVersion 10.15.7
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "brew update"
        run: brew update      
      - name: "check on brew version"
        run: brew --version   #Homebrew 2.5.12   
      - name: "Get OS X System Version"
        run: sw_vers       
      - name: "Get Mac System Details with system_profiler"
        run: system_profiler | more  
      - name: "osfingerprinting"
        run: uname -a   
        # cuckoo    
        # Installing Python libraries (on Mac OS X)
        # https://cuckoo.sh/docs/installation/host/requirements.html                            
      - name: "cuckoo - Installing Python libraries"
        run: brew install libmagic cairo pango openssl
      - name: "cuckoo - expose the openssl header files in the standard GCC/Clang include directory"
        run: cd /usr/local/include && ln -s ../opt/openssl/include/openssl . 
