

name: "macOS CI workflow"


on:
  push:
    branches: [ dev ]
  # pull_request:
  #   branches: [ githubactions_powershell ]


jobs:

  macos-latest-rust:
      name: "macos-latest macos-latest 10.15.7 rust"
      runs-on: macos-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "brew update"
        run: brew update      
      - name: "check on brew version"
        run: brew --version   #Homebrew 2.5.12   
      - name: "Install rustup"
        run:   curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: "add Rust to your system PATH manually"
        run:   | 
          source $HOME/.cargo/env
          rustup update
          rustc --version
          cargo --version
      # https://doc.rust-lang.org/book/ch01-02-hello-world.html
      - name: "Hello World rust"
        run:   | 
          mkdir ~/projects
          cd ~/projects
          mkdir hello_world
          cd hello_world
          cat <<EOT | sudo tee main.rs
          fn main() {
          println!("Hello, world!");
          }
          EOT
          ls -lai
          rustc main.rs
          ls -lai
          ./main
      # https://doc.rust-lang.org/book/ch01-03-hello-cargo.html
      - name: "Hello Cargo"
        run:   | 
          ls -lai
          cd ~/projects
          cargo --version
          cargo new hello_cargo
          cd hello_cargo
          ls -lai
          cat Cargo.toml
          cat src/main.rs
          cargo check
          cargo build
          ./target/debug/hello_cargo
          cargo check
          cargo run

  # macos-latest-python-venv:
  #     name: "macos-latest macos-latest 10.15.7 python venv"
  #     runs-on: macos-latest
  #     steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: "brew update"
  #       run: brew update      
  #     - name: "check on brew version"
  #       run: brew --version   #Homebrew 2.5.12   
  #     - name: "python --version"
  #       run:   python --version #Python 2.7.18
  #     - name: "pip install virtualenv"
  #       run:   pip install virtualenv               
  #     - name: "echo $PATH"
  #       run:   echo $PATH
  #     - name: "add to $PATH"
  #       run:   export PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:$PATH"              
  #     - name: "source ~/.bash_profile"
  #       run:   source ~/.bash_profile
  #     - name: "echo $PATH"
  #       run:   echo $PATH       
      # - name: "virtualenv --version" 
      #   run:   virtualenv --version  #virtualenv: command not found       
      # - name: "virtualenv -p $(which python2) ~venvpython2x"
      #   run:   virtualenv -p $(which python2) ~~venvpython2x
      # - name: "source ~venvpython2x/bin/activate"
      #   run:   source ~venvpython2x/bin/activate     
      # - name: "source ~venvpython2x/bin/activate"
      #   run:   source ~venvpython2x/bin/activate    

      
  # macos-latest-docker:
  #     name: "macos-latest macos-latest 10.15.7"
  #     runs-on: macos-latest
  #     steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: "brew update"
  #       run: brew update      
  #     # - name: "brew upgrade"
  #     #   run: brew upgrade
  #     - name: "check on brew version"
  #       run: brew --version   #Homebrew 2.5.12   
  #     - name: "brew cask list"
  #       run:   brew list --cask #Warning: Calling brew cask list is deprecated! Use brew list [--cask] instead.
  #     - name: "brew list"
  #       # run: brew list #List all the installed formulas
  #       run: brew list --formula #List all the installed formulas
  #       # Calling `brew list` to only list formulae is disabled! Use `brew list --formula` instead
  #     - name: "Get OS X System Version"
  #       run: sw_vers       
  #     - name: "Get Mac System Details with system_profiler"
  #       run: system_profiler | more  
  #     - name: "osfingerprinting"
  #       run: uname -a    
  #     - name: "Download and install Docker Community Edition"
  #       run: |
  #         #Calling brew cask install is disabled! Use brew install [--cask] instead.  
  #         #brew cask install docker 
  #         brew --cask install docker   
  #     - name: "run hello-world"
  #       run: |
  #         docker run hello-world                                     
  #     # - name: "brew doctor"
  #     #   run: |
  #     #     brew doctor #Check brew for potential problems 

  # macos-latest:
  #     name: "macos-latest macos-latest 10.15.7"
  #     runs-on: macos-latest
  #     steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: "brew update"
  #       run: brew update      
  #     # - name: "brew upgrade"
  #     #   run: brew upgrade
  #     - name: "check on brew version"
  #       run: brew --version   #Homebrew 2.5.12   
  #     - name: "brew cask list"
  #       run:   brew list --cask #Warning: Calling brew cask list is deprecated! Use brew list [--cask] instead.
  #     - name: "brew list"
  #       # run: brew list #List all the installed formulas
  #       run: brew list --formula #List all the installed formulas
  #       # Calling `brew list` to only list formulae is disabled! Use `brew list --formula` instead
  #     - name: "Get OS X System Version"
  #       run: sw_vers       
  #     - name: "Get Mac System Details with system_profiler"
  #       run: system_profiler | more  
  #     - name: "osfingerprinting"
  #       run: uname -a                           
  #     # - name: "brew doctor"
  #     #   run: |
  #     #     brew doctor #Check brew for potential problems 

  # macos-110:
  #     name: "macos-11.0"
  #     runs-on: macos-11.0 # ProductVersion 11.0.1 macOS Big Sur
  #     steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: "brew update"
  #       run: brew update      
  #     # - name: "brew upgrade"
  #     #   run: brew upgrade
  #     - name: "check on brew version"
  #       run: brew --version   #Homebrew 2.5.12   
  #     - name: "brew cask list"
  #       run:   brew list --cask #Warning: Calling brew cask list is deprecated! Use brew list [--cask] instead.
  #     - name: "brew list"
  #       # run: brew list #List all the installed formulas
  #       run: brew list --formula #List all the installed formulas
  #       # Calling `brew list` to only list formulae is disabled! Use `brew list --formula` instead
  #     - name: "Get OS X System Version"
  #       run: sw_vers       
  #     - name: "Get Mac System Details with system_profiler"
  #       run: system_profiler | more  
  #     - name: "osfingerprinting"
  #       run: uname -a                           
  #     # - name: "brew doctor"
  #     #   run: |
  #     #     brew doctor #Check brew for potential problems 

  # macos-1015:
  #     name: "macos-10.15"
  #     runs-on: macos-10.15 # ProductVersion 10.15.7
  #     steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: "brew update"
  #       run: brew update      
  #     # - name: "brew upgrade"
  #     #   run: brew upgrade
  #     - name: "check on brew version"
  #       run: brew --version   #Homebrew 2.5.12   
  #     - name: "brew cask list"
  #       run:   brew list --cask #Warning: Calling brew cask list is deprecated! Use brew list [--cask] instead.
  #     - name: "brew list"
  #       # run: brew list #List all the installed formulas
  #       run: brew list --formula #List all the installed formulas
  #       # Calling `brew list` to only list formulae is disabled! Use `brew list --formula` instead
  #     - name: "Get OS X System Version"
  #       run: sw_vers       
  #     - name: "Get Mac System Details with system_profiler"
  #       run: system_profiler | more  
  #     - name: "osfingerprinting"
  #       run: uname -a                           
  #     # - name: "brew doctor"
  #     #   run: |
  #     #     brew doctor #Check brew for potential problems 
