

name: "macports macOS CI workflow"


on:
  push:
    branches: [ dev ]



jobs:

  macos-macports-latest:
      name: "MacPorts macos-latest macos-latest 10.15.7"
      runs-on: macos-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "brew update"
        run: brew update      
      # - name: "brew upgrade"
      #   run: brew upgrade
      - name: "check on brew version"
        run: brew --version   #Homebrew 2.5.12 
      - name: "check on xcode version"
        run: |
          /usr/bin/xcodebuild -version
          which xcodebuild
          xcodebuild -version
        # https://guide.macports.org/#installing.xcode  
      - name: "MacPorts Source Install"
        run: |
          export MACPORTS_VERSION="2.7.1"
          echo $MACPORTS_VERSION 
          # curl -O https://distfiles.macports.org/MacPorts/MacPorts-2.7.1.tar.bz2          
          curl -O https://distfiles.macports.org/MacPorts/MacPorts-$MACPORTS_VERSION.tar.bz2          
          # tar xf MacPorts-2.7.1.tar.bz2
          tar xf MacPorts-$MACPORTS_VERSION.tar.bz2
          # cd MacPorts-2.7.1/
          cd MacPorts-$MACPORTS_VERSION/
          ./configure
          make
          sudo make install
          # port version #port: command not found
      - name: "MacPorts Shell Configuration"
        run: |
          echo $PATH          
          export PATH=/opt/local/bin:/opt/local/sbin:$PATH
          port version
          sudo port -v selfupdate
      - name: "brew cask list"
        run:   brew list --cask #Warning: Calling brew cask list is deprecated! Use brew list [--cask] instead.
      - name: "brew list"
        # run: brew list #List all the installed formulas
        run: brew list --formula #List all the installed formulas
        # Calling `brew list` to only list formulae is disabled! Use `brew list --formula` instead
      - name: "Get OS X System Version"
        run: sw_vers       
      - name: "Get Mac System Details with system_profiler"
        run: system_profiler | more  
      - name: "osfingerprinting"
        run: uname -a                           
      - name: "brew doctor"
        run: |
          brew doctor #Check brew for potential problems           


